### ISSUE TITLE
Ubuntu package?

### ISSUE THREAD

**Issue by shimmy568** [PhrozenByte/rmtrash#11]
It would be nice to be able to install on Ubuntu seems like a useful tool.

**Comment by shimmy568** [comment]
Never-mind forget I said anything. We have `trash-cli` 

:man_facepalming:

**Comment by PhrozenByte** [comment]
Exactly. Since this is just a wrapper script for `trash-cli` to support some of the super convenient options of `rm`, and since it's practically required to add an `alias` to your `.bashrc` (a package can't resp. really shouldn't do that), a package IMO isn't really necessary :smiley:
