### ISSUE TITLE
--ignore-fail-on-non-empty for rmdirtrash deletes non-empty directories

### ISSUE THREAD

**Issue by Thyrum** [PhrozenByte/rmtrash#15]
The `--ignore-fail-on-non-empty` option for `rmdir` only disables the error messages. `rmdir` itself will still never delete non-empty directories, even if `--ignore-fail-on-non-empty` is set. The `rmdirtrash` script however does delete non-empty directories when `--ignore-fail-on-non-empty` is set.

**Comment by PhrozenByte** [comment]
Indeed. This script is nearly 10 years old, but you're the first one spotting this :smile: Fixed in [v1.14](https://github.com/PhrozenByte/rmtrash/releases/tag/v1.14). Thanks! :+1:
