### ISSUE TITLE
script does not reset FILES variable

### ISSUE THREAD

**Issue by purarue** [PhrozenByte/rmtrash#18]
Hi, thanks for the great tool, been using it for a while now.

Recently I set the `FILES` environment variable in my shell startup to "${HOME}/Files", it being a sort of backup/data directory for me, so I could use it in other scripts

```bash
# I want a separate Files directory that has more backup-like
# files that I dont need on all my machines
#
# that way I can nicely sync my ~/Documents across machines
export FILES="${HOME}/Files"
```

When I did so, since the `FILES` variable is used [here](https://github.com/PhrozenByte/rmtrash/blob/master/rmtrash#L600-L602) without setting it to something like `FILES=()` or running `declare -a FILES=()` at the top, while trying to remove an unrelated file, it gives me an error like (or asks me for a useless prompt):

```
[ ~/Downloads/testdir ] $ touch file                                 
[ ~/Downloads/testdir ] $ rmtrash -ir test
rmtrash: descend into directory '/home/sean/Files'? y
rmtrash: remove regular empty file 'test'? y
[ ~/Downloads/testdir ] $ touch test 
[ ~/Downloads/testdir ] $ rmtrash -i test 
rmtrash: cannot remove '/home/sean/Files': Is a directory
rmtrash: remove regular empty file 'test'? y
```

I think this can be fixed by adding `FILES=()` just above that, created a PR if that works for you

**Comment by PhrozenByte** [comment]
Good catch! :+1: Thank you very much, fixed by your PR #19 and released as v1.15 :tada: :+1:
