### ISSUE TITLE
alias rm, does not work in scripts

### ISSUE THREAD

**Issue by nicesw123** [PhrozenByte/rmtrash#2]
Hi,

thanks for this nice wrapper of trash_cli.

But alias definitions do not work in scripts. Example...

Using 

``` bash
alias rm='rmtrash'
alias rmdir='rmdirtrash'
alias sudo='sudo '
```

will not work in a script such as 
- **`myscript.sh`**
  
  ``` bash
  #!/usr/bin/env bash
  
  rm testfile.txt
  ```
#### Possible solution

Put a script-version of `rm` and `rmdir` into `/usr/local/bin` as follows:
- **`/usr/local/bin/rm`**
  
  ``` bash
  #!/usr/bin/env bash
  
  /usr/local/bin/rmtrash "$@"
  ```
- **`/usr/local/bin/rmdir`**
  
  ``` bash
  #!/usr/bin/env bash
  
  /usr/local/bin/rmdirtrash "$@"
  ```

(Needs `rmtrash` and `rmdirtrash` in `/usr/local/bin`.)

Then **important !!**
- Change [`rmtrash` line 186](https://github.com/PhrozenByte/rmtrash/blob/b4c46157ad5c90a5fb9e6e109e67b06a254c0709/rmtrash#L186) to
  
  ``` bash
  PATH=/usr/bin:/bin   RM_CMD="$(which "rm")"
  ```
- Change [`rmdirtrash` line 161](https://github.com/PhrozenByte/rmtrash/blob/b4c46157ad5c90a5fb9e6e109e67b06a254c0709/rmdirtrash#L161) to
  
  ``` bash
  PATH=/usr/bin:/bin   RM_CMD="$(which "rmdir")"
  ```

From [bash manual section 3.7.4](http://www.gnu.org/software/bash/manual/bash.html#Environment): _"The environment for any simple command or function may be augmented temporarily by prefixing it with parameter assignments, as described in Shell Parameters. These assignment statements affect only the environment seen by that command. "_

So this finds the standard `rm` and `rmdir` which is what we want.
(This is also a solution, for your warning ([link](https://github.com/PhrozenByte/rmtrash/commit/1880753f717dba5815ab8ed9a6431f2e75ed068a#diff-04c6e90faac2675aa89e2176d2eec7d8R72)) about: _" Never name `rmtrash`s scriptfile `rm` - this will replace `rm` and is definitly not what you actually want!"_)

What do you think?

Oh some questions:
- Is there any other way you know, of making `rm` in scripts (`myscript.sh`) work with `rmtrash` ? (I think aliases just don't work).
- Will you consider to change [`rmtrash` line 186](https://github.com/PhrozenByte/rmtrash/blob/b4c46157ad5c90a5fb9e6e109e67b06a254c0709/rmtrash#L186) and [`rmdirtrash` line 161](https://github.com/PhrozenByte/rmtrash/blob/b4c46157ad5c90a5fb9e6e109e67b06a254c0709/rmdirtrash#L161) as shown above?

Thanks.

**Comment by nicesw123** [comment]
> - Change [`rmtrash` line 186](https://github.com/PhrozenByte/rmtrash/blob/b4c46157ad5c90a5fb9e6e109e67b06a254c0709/rmtrash#L186) to
> 
> ``` bash
> PATH=/usr/bin:/bin   RM_CMD="$(which "rm")"
> ```
> - Change [`rmdirtrash` line 161](https://github.com/PhrozenByte/rmtrash/blob/b4c46157ad5c90a5fb9e6e109e67b06a254c0709/rmdirtrash#L161) to
> 
> ``` bash
> PATH=/usr/bin:/bin   RM_CMD="$(which "rmdir")"
> ```

One should mention that the offical locations of `rm` and `rmdir` is always in `/bin`.
This is standardized in the [Filesystem Hierarchy Standard](https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html#binEssentialUserCommandBinaries) ([link](https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html#binEssentialUserCommandBinaries)).

**Comment by PhrozenByte** [comment]
This behaviour is intended, you really **mustn't** rename `rmtrash` to `rm` (or anything similiar like creating a "wrapper wrapper script" named `rm`). I even don't recommend to use `rmtrash` in any other scripts, even though `rmtrash` doesn't prevent you from doing this (simply call `rmtrash`). So, if you want to use `rmtrash` in your own scripts, call `rmtrash` instead of `rm`. If you want to use `rmtrash` in foreign scripts - sorry, you really shouldn't do such things. Anyway, just a little hint: If you call `rmtrash` with a custom `PATH` variable, `which` (to find `RM_CMD`) will use this variable.

**Comment by nicesw123** [comment]
>  Anyway, just a little hint: If you call rmtrash with a custom PATH variable, which (to find RM_CMD) will use this variable.

Yes, this is exactly the point!

I propose to set the PATH variable in a _single line only_... within `rmtrash`

> > - Change [`rmtrash` line 186](https://github.com/PhrozenByte/rmtrash/blob/b4c46157ad5c90a5fb9e6e109e67b06a254c0709/rmtrash#L186) to
> > 
> > ``` bash
> > PATH=/usr/bin:/bin   RM_CMD="$(which "rm")"
> > ```

Theoretically one can even use a hardcoded version...

``` bash
RM_CMD=/bin/rm
```

... as every good distro (conforming to FHS -- [link](https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html#binEssentialUserCommandBinaries)) will work; but specifying PATH to be `/usr/bin:/bin` (first `/usr/bin` then `/bin`) is a bit more flexible.

(Same for `rmdirtrash`)

**Comment by PhrozenByte** [comment]
Following good practice `rmtrash` doesn't hardcode any paths, neither to `/bin/rm` specifically nor a hardcoded `PATH`. Furthermore your intention is, as stated in the `README.md`, not intended to work. Sorry.

**Comment by nicesw123** [comment]
OK but hang-on. I was just thinking about your comment some more...

> Anyway, just a little hint: If you call rmtrash with a custom PATH variable, which (to find RM_CMD) will use this variable.

Yip, your're right! That's all I need.

I'll therefore go like this, to solve it:
Put a script-version of `rm` and `rmdir` into `/usr/local/bin` as follows:
- **`/usr/local/bin/rm`**
  
  ``` bash
  #!/usr/bin/env bash
  
  PATH=/usr/bin:/bin   /usr/local/bin/rmtrash "$@"
  ```
- **`/usr/local/bin/rmdir`**
  
  ``` bash
  #!/usr/bin/env bash
  
  PATH=/usr/bin:/bin   /usr/local/bin/rmdirtrash "$@"
  ```

Then your nice script can stay as it is, and I can have rm working in scripts as I want.
Win win!

**Comment by nicesw123** [comment]
Damn I wrote too quickly...

The following...
> * **`/usr/local/bin/rm`**
> ```bash
#!/usr/bin/env bash
PATH=/usr/bin:/bin   /usr/local/bin/rmtrash "$@"
```

... does not work as I intended.
For some strange reason, the PATH I want to pass in, `PATH=/usr/bin:/bin` is ignored.
I don't (yet) know why...

**Comment by nicesw123** [comment]
Ah I had some brief problems myself... since I wrote `PATH=/usr/bin:bin` (Spot the error -> the `bin` was missing the slash! Should be `PATH=/usr/bin:/bin`).

Now everything is working fine, according to the method as mentioned one [comment](https://github.com/PhrozenByte/rmtrash/issues/2#issuecomment-142914095) higher.

So perfect.

**Comment by nicesw123** [comment]
ok... I now think it is extremely dangerous if administrative programs run as root (e.g. scripts in `/sbin`) do not have the real `/bin/rm`.

If one really wants to use the scripts above then rather like this:
- **`/usr/local/bin/rm`**

``` bash
#!/usr/bin/env bash

is_root () {
    return $(id -u)
}

if which trash-put &>/dev/null; then                  ## trash-put exists
    if is_root; then
    PATH=/usr/bin:/bin   rm "$@"                      ## root should use normal rm
    else
    PATH=/usr/bin:/bin   /usr/local/bin/rmtrash "$@"  ## user should use rmtrash
    fi
else
    PATH=/usr/bin:/bin   rm "$@"
fi
```
- **`/usr/local/bin/rmdir`**

``` bash
#!/usr/bin/env bash

is_root () {
    return $(id -u)
}

if which trash-put &>/dev/null; then                     ## trash-put exists
    if is_root; then
    PATH=/usr/bin:/bin   rmdir "$@"                      ## root should use normal rmdir
    else
    PATH=/usr/bin:/bin   /usr/local/bin/rmdirtrash "$@"  ## user should use rmdirtrash
    fi
else
    PATH=/usr/bin:/bin   rmdir "$@"
fi
```

I'm now using the alias versions (not my own `rm` and `rmdir` scripts [shown above]). I have to make sure that any scripts calling `rm`, are very careful, since such scripts will call the real `/bin/rm`.

**Comment by PhrozenByte** [comment]
Again, just a little hint apart from my ongoing warning about doing something like that: Consider using the `--forbid-root` parameter.
