### ISSUE TITLE
trash symlinks doesn't work

### ISSUE THREAD

**Issue by samjewell** [PhrozenByte/rmtrash#3]
I have a symlink `me` which points at `mydir/me`

I them remove `mydir/me` from my system.

After that I try to remove the symlink:

```
$ rmtrash me
```

Observed:

```
me: File or directory does not exist.
```

Expected:
[no output] - trashing succeeded.

This is the expected output because it's what `rm` would do in this scenario, as far as I've seen.

**Comment by PhrozenByte** [comment]
Hmmm... Yeah, there's definitely something going wrong. Unfortunately I'm not able to reproduce this. Can you please give me a step-by-step tutorial on how to trigger this issue?

This is what I was trying (what successfully trashes the broken symlink for me):

```
$ mkdir mydir
$ touch mydir/me
$ ln -s mydir/me me
$ /bin/rm mydir/me
$ rmtrash -v me
rmtrash: executing `/usr/bin/trash-put --verbose "/home/daniel/me"`
trash-put: `/home/daniel/me' trashed in ~/.local/share/Trash
```

**Comment by PhrozenByte** [comment]
Wow, time flies! rmtrash 1.11 is from May 2015, that's probably the reason why I didn't remember this... I've fixed this (or a very similar) issue with rmtrash 1.11, see https://github.com/PhrozenByte/rmtrash/releases/tag/v1.11. Are you using the latest version? If not, please try it with rmtrash 1.11. If the issue persists, there's yet another issue with broken symlinks - however, I'm then still not able to reproduce it.

**Comment by samjewell** [comment]
Oh wow, my bad - I just ran `brew install rmtrash` - I'm running someone else's version 😢 

```
rmtrash version 0.3.3
    Copyright 2003 Night Productions
```

Seems I should try yours instead! I'm guessing this one isn't on Homebrew yet?

**Comment by PhrozenByte** [comment]
Afaik not, no.
