### ISSUE TITLE
Bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by allaudin** [PhrozenByte/rmtrash#4]
Deleting a file (using **MINGW** windows) throws following error

`/usr/bin/rmtrash: /c/cygwin64/bin/trash-put: /usr/bin/python2.7: bad interpreter: No such file or directory`

**Comment by PhrozenByte** [comment]
`rmtrash` is a wrapper script for [andreafrancia's `trash-cli`](https://github.com/andreafrancia/trash-cli) project which handles the actual process of trashing files, thus you need a working instance of the `trash-put` command on your system.

Try

```
$ trash-put /path/to/some/file/to/trash
```

If this throws the same error, please refer to [`andreafrancia/trash-cli`](https://github.com/andreafrancia/trash-cli) and report this issue there.
