### ISSUE TITLE
`-r` option not working

### ISSUE THREAD

**Issue by kleinjm** [PhrozenByte/rmtrash#6]
```
➜ del -r spec/controllers
rmtrash: illegal option -- r
USAGE: rmtrash [-h] [-v] [-u USERNAME] FILENAME
```
Awesome package but I can't seem to get it to work for directories. Let me know what debug info is helpful, thanks!

**Comment by PhrozenByte** [comment]
This is `rmtrash`, a wrapper shell script for `trash-cli` (Linux), see our `README.md`. Please note that there are some programs of the same name out there, you're probably talking about the Homebrew/MacPorts/nightproductions `rmtrash` for OS X.
